// same server/shared/src/lib/exceptions/graphql.error.ts
export enum GraphqlErrorCode {
  'INTERNAL_SERVER_ERROR' = 'INTERNAL_SERVER_ERROR',
  'NOT_FOUND_ERROR' = 'NOT_FOUND_ERROR',
  'BAD_REQUEST_ERROR' = 'BAD_REQUEST_ERROR',
  'UNSUPPORTED_MEDIATYPE_ERROR' = 'UNSUPPORTED_MEDIATYPE_ERROR',
  'FORBIDDEN_ERROR' = 'FORBIDDEN_ERROR',
  'CONFLICT_ERROR' = 'CONFLICT_ERROR',
  'METHOD_NOT_ALLOWED_ERROR' = 'METHOD_NOT_ALLOWED_ERROR',
  'REQUEST_TIMEOUT_ERROR' = 'REQUEST_TIMEOUT_ERROR',
  'UNAUTHORIZED_ERROR' = 'UNAUTHORIZED_ERROR',
  'NOT_IMPLEMENTED_ERROR' = 'NOT_IMPLEMENTED_ERROR',
  'PAYLOAD_TOO_LARGE_ERROR' = 'PAYLOAD_TOO_LARGE_ERROR',
  'VALIDATION_ERROR' = 'VALIDATION_ERROR',
  'RATE_LIMIT_ERROR' = 'RATE_LIMIT_ERROR',
}